### ISSUE TITLE
How to add an other proxy before

### ISSUE THREAD

**Issue by CondormanFr** [pastakhov/compose-mediawiki-ubuntu#8]
Hi,
Nice work. I'm able to make it working alone.
But in my case, In my docker-compose file with other services, I want mediawiki available behind an nginx proxy  at the address : http://docker/wiki

For nginx (listening on port 80), I my default.conf, I have : 

```
location /wiki {
            proxy_pass http://proxy:8090;
            proxy_set_header X-Real-IP  $remote_addr;
            proxy_set_header HOST $host;
            proxy_set_header X-Forwarded-For $remote_addr;
```

and in the docker compose, i set : 
```
proxy:
        image: pastakhov/varnish-mediawiki:1.0
        depends_on:
            - web
            - restbase
        ports:
            - "8090:80"
        networks:
          - prodnetwork    
        environment:
            - PROXY_BACKEND_web=web:80
            - PROXY_BACKEND_restbase=restbase:7231
            - PROXY_RESTBASE_BACKEND=restbase
            - PROXY_RESTBASE_URL=^/api/rest_v1
            - PROXY_RESTBASE_SUB=/{backend_hint}/v1

    web:
        build: 
            context: ./web
            dockerfile: Dockerfile
        depends_on:
            - db
            - elasticsearch
            - memcached
            - parsoid
            - restbase
        networks:
          - prodnetwork    
        environment:
            - MW_SITE_SERVER=//docker/wiki
            - MW_SITE_NAME=MediaWiki

```
docker is the name of my host.

In nginx log, I have :  
```
 2017-11-01T07:24:05.623517833Z 2017/11/01 07:24:05 [error] 10#10: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.60.5, server: docker, request: "GET /wiki/Accueil HTTP/1.1", upstream: "http://172.20.0.21:8090/wiki/Accueil", host: "docker"
2017-11-01T07:24:05.623772705Z 192.168.60.5 - - [01/Nov/2017:07:24:05 +0000] "GET /wiki/Accueil HTTP/1.1" 502 537 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" "-"
```

Thanks for your help
